baseURL = 'mrgrossman.com'
languageCode = 'en-us'
title = 'MATTHEW GROSSMAN'
# theme = "PaperMod"

# [params]
# hidemeta = false

# [params.profileMode]
# enabled = true
# title = "MATTHEW GROSSMAN"
# subtitle = "product/infra BE engineer"
# imageUrl = "<image link>"
# imageTitle = "<title of image as alt>"
# imageWidth = 120
# imageHeight = 120

#   [[params.profileMode.buttons]]
#   name = "Linkedin"
#   url = "https://www.linkedin.com/in/matthewryangrossman/"

#   [[params.profileMode.buttons]]
#   name = "Github"
#   url = "https://github.com/matthewgrossman"

# [[params.socialIcons]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/matthewryangrossman/"

# [[params.socialIcons]]
# name = "Github"
# url = "https://github.com/matthewgrossman"
