site_name: Matthew Grossman
site_description: Personal Website
site_url: https://mrgrossman.com
plugins: []
theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.webp
  palette: false
  font: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.snippets
