name: ci
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install `mkdocs`
        run: pip install mkdocs-material
      - name: Build
        run: mkdocs build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.FINE_GRAINED_TOKEN }}
          folder: site
          single-commit: true
          repository-name: matthewgrossman/matthewgrossman.github.io
