name: ci 
on:
  push:
    branches:
      - master 
      - main
      - hugo-again
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: master
          repository-name: matthewgrossman/matthewgrossman.github.io
